### PR TITLE
Upgrade/patch modern version

### PR DESCRIPTION
**Pull request by zubin**
Context
---

Market requires [SEO functionality](https://webmasters.googleblog.com/2011/09/pagination-with-relnext-and-relprev.html) which does not exist in [official will_paginate version](https://github.com/mislav/will_paginate) (hence this fork).

It uses deprecated hash finder syntax which is deprecated in rails 4.

Unfortunately the [upstream fork](https://github.com/lloydmeta/will_paginate) is unmaintained, and rebasing against it or the official version generates a ton of conflicts.

Solution
---

Hard reset against the current version, then manually add the code which we need (see last commit).

### CODE REVIEW

**Comment by shevaun** [comment]
seems like a good idea 👍

**Comment by zubin** [comment]
Is the following acceptable for merging this unmergeable PR into master or is there a better/preferred way? 

```
git checkout master
git reset --hard origin/upgrade
git push -f
```

**Comment by shevaun** [comment]
Will doing that break the current version of the gem?

**Comment by zubin** [comment]
@shevaun Instead of brutally replacing master, I've decided to reference the branch from `Gemfile` (at least until we're confident about losing history).

**Pull request closed without merging**
